import { Food } from '../types';

export type { Food };

function r(foodId: string, id: string, name: string, emoji: string, difficulty: 'easy' | 'medium', prepTime: string, ageRange: string, ingredients: string[], steps: string[], tip: string) {
  return { id: `${foodId}-${id}`, foodId, name, emoji, difficulty, prepTime, ageRange, ingredients, steps, tip };
}

export const FOODS: Food[] = [
  {
    id: 'carrot', name: 'Carrot', emoji: '🥕', category: 'vegetable', texture: 'crunchy', introductionDays: 12,
    tip: 'Start with carrot sticks and hummus dip',
    description: 'A crunchy orange root that grows underground — rabbits love it and so can you!',
    recipes: [
      r('carrot', 'sticks', 'Carrot Sticks & Hummus', '🥕', 'easy', '5 min', '12+ months',
        ['1 carrot, peeled', '2 tbsp hummus', 'pinch of salt'],
        ['Cut carrot into thin sticks', 'Serve with hummus on the side', 'Let your child dip it themselves'],
        'Self-dipping gives kids control, which makes new foods less scary.'),
      r('carrot', 'glazed', 'Honey Butter Carrots', '🍯', 'easy', '12 min', '12+ months',
        ['1 cup sliced carrots', '1 tbsp butter', '1 tsp honey'],
        ['Boil carrot slices until soft (8 min)', 'Melt butter and honey in the pan', 'Toss carrots in the glaze and cool before serving'],
        'Natural sweetness makes the first bite easier to say yes to.'),
      r('carrot', 'muffins', 'Hidden Carrot Muffins', '🧁', 'medium', '25 min', '18+ months',
        ['1 cup grated carrot', '1 cup muffin batter (any base)', '1 tsp cinnamon'],
        ['Preheat oven to 180°C', 'Stir grated carrot and cinnamon into batter', 'Bake in muffin tin for 18 min'],
        'A great stepping stone when a food is still being refused whole.'),
    ],
  },
  {
    id: 'broccoli', name: 'Broccoli', emoji: '🥦', category: 'vegetable', texture: 'mixed', introductionDays: 12,
    tip: 'Call them "little trees" — kids love the story',
    description: 'A tiny tree-shaped vegetable that\'s secretly a superhero for strong bodies.',
    recipes: [
      r('broccoli', 'trees', 'Tiny Trees with Cheese Dip', '🧀', 'easy', '5 min', '12+ months',
        ['1 small broccoli floret', '2 tbsp cream cheese', 'pinch of salt'],
        ['Steam floret for 4 minutes until soft but not mushy', 'Mix cream cheese with a pinch of salt', 'Call it a "tiny tree" and serve with dip on the side'],
        'Kids are more likely to try food they helped prepare — let them dip!'),
      r('broccoli', 'soup', 'Green Superhero Soup', '🍵', 'medium', '15 min', '18+ months',
        ['1 cup broccoli', '1 potato', '2 cups vegetable broth'],
        ['Boil broccoli and potato until soft (10 min)', 'Blend until smooth', 'Add a swirl of cream and call it superhero soup'],
        'Hiding vegetables in soups is a great stepping stone before whole pieces.'),
      r('broccoli', 'bites', 'Cheesy Broccoli Bites', '🧆', 'medium', '20 min', '18+ months',
        ['1 cup steamed broccoli', '1/2 cup cheese', '1 egg'],
        ['Preheat oven to 200°C', 'Chop broccoli finely and mix with cheese and egg', 'Form small balls and bake 15 min'],
        'These freeze well — make a batch and reheat as needed!'),
    ],
  },
  {
    id: 'sweetpotato', name: 'Sweet Potato', emoji: '🍠', category: 'vegetable', texture: 'soft', introductionDays: 12,
    tip: 'Roast with cinnamon and butter — naturally sweet',
    description: 'A naturally sweet orange potato that tastes like dessert but is full of goodness.',
    recipes: [
      r('sweetpotato', 'fries', 'Sweet Potato Fries', '🍟', 'easy', '25 min', '12+ months',
        ['1 sweet potato, cut into wedges', '1 tbsp oil', 'pinch of salt'],
        ['Preheat oven to 200°C', 'Toss wedges in oil and salt', 'Bake 20–25 min, flipping halfway'],
        'The familiar fry shape makes this an easy first sweet potato win.'),
      r('sweetpotato', 'mash', 'Cinnamon Sweet Potato Mash', '🍠', 'easy', '15 min', '12+ months',
        ['1 sweet potato', '1 tbsp butter', 'pinch of cinnamon'],
        ['Boil peeled, cubed sweet potato until soft', 'Mash with butter and cinnamon', 'Serve warm'],
        'Serve next to a food they already love to lower the pressure.'),
      r('sweetpotato', 'soup', 'Creamy Sweet Potato Soup', '🥣', 'medium', '20 min', '18+ months',
        ['1 sweet potato', '2 cups vegetable broth', '2 tbsp cream'],
        ['Boil cubed sweet potato in broth until soft', 'Blend until smooth', 'Stir in cream before serving'],
        'A smooth soup is gentle for kids who are sensitive to lumpy textures.'),
    ],
  },
  {
    id: 'peas', name: 'Peas', emoji: '🟢', category: 'vegetable', texture: 'mushy', introductionDays: 12,
    tip: 'Frozen peas thawed — kids like the pop texture',
    description: 'Tiny green balls that pop in your mouth — like nature\'s candy buttons.',
    recipes: [
      r('peas', 'mash', 'Minty Mushy Peas', '🟢', 'easy', '8 min', '12+ months',
        ['1/2 cup peas', '1 tbsp butter', 'pinch of mint (optional)'],
        ['Boil peas for 4 minutes', 'Mash lightly with butter', 'Serve warm on toast or alone'],
        'Mashing peas slightly makes them less likely to roll off the spoon.'),
      r('peas', 'pasta', 'Pea & Parmesan Pasta', '🍝', 'easy', '12 min', '18+ months',
        ['1/2 cup peas', '1 cup cooked pasta', '2 tbsp parmesan'],
        ['Boil peas with the pasta for the last 3 minutes', 'Drain and toss with butter and parmesan', 'Serve warm'],
        'Mixing into a beloved food is a gentle bridge to acceptance.'),
      r('peas', 'soup', 'Pea & Ham Soup', '🍵', 'medium', '15 min', '18+ months',
        ['1 cup peas', '2 cups stock', '2 tbsp cream'],
        ['Simmer peas in stock for 8 minutes', 'Blend until smooth', 'Stir in cream'],
        'A smooth soup hides the pop texture for sensitive eaters.'),
    ],
  },
  {
    id: 'tomato', name: 'Tomato', emoji: '🍅', category: 'vegetable', texture: 'mixed', introductionDays: 12,
    tip: 'Cherry tomatoes halved — small and fun to eat',
    description: 'A juicy red fruit-vegetable that bursts with flavor in one little bite.',
    recipes: [
      r('tomato', 'caprese', 'Caprese Skewers', '🧀', 'easy', '5 min', '18+ months',
        ['1 cherry tomato', '1 mozzarella ball', '1 basil leaf'],
        ['Thread tomato, mozzarella, and basil onto a small stick', 'Serve as a fun finger food'],
        'Finger foods on sticks feel like a game, not a meal.'),
      r('tomato', 'sauce', 'Simple Tomato Pasta Sauce', '🍝', 'easy', '15 min', '12+ months',
        ['1 cup chopped tomato', '1 tbsp butter', 'pinch of salt'],
        ['Simmer tomato with butter for 10 minutes', 'Blend smooth if needed', 'Toss with pasta'],
        'A sauce is a low-pressure way to introduce the flavor first.'),
      r('tomato', 'soup', 'Cozy Tomato Soup', '🥣', 'medium', '20 min', '18+ months',
        ['2 cups chopped tomato', '1 cup broth', '2 tbsp cream'],
        ['Simmer tomato in broth for 12 minutes', 'Blend until smooth', 'Stir in cream and serve with toast'],
        'Pair with a dippable bread stick for extra comfort.'),
    ],
  },
  {
    id: 'spinach', name: 'Spinach', emoji: '🥬', category: 'vegetable', texture: 'soft', introductionDays: 12,
    tip: 'Hide in smoothies first, then blend into scrambled eggs',
    description: 'Popeye\'s favorite leafy green — it makes you strong like a superhero!',
    recipes: [
      r('spinach', 'smoothie', 'Green Power Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['1 handful spinach', '1 banana', '1 cup milk'],
        ['Blend spinach, banana, and milk until smooth', 'Pour into a fun cup with a straw'],
        'The banana hides the flavor while the bright color stays fun.'),
      r('spinach', 'eggs', 'Spinach Scrambled Eggs', '🍳', 'easy', '8 min', '12+ months',
        ['1 handful chopped spinach', '2 eggs', 'pinch of cheese'],
        ['Wilt spinach in a pan for 1 minute', 'Add beaten eggs and cheese', 'Scramble until cooked through'],
        'Finely chopped spinach blends into a familiar texture.'),
      r('spinach', 'quesadilla', 'Spinach & Cheese Quesadilla', '🧀', 'medium', '10 min', '18+ months',
        ['1 handful spinach', '1 tortilla', '1/2 cup cheese'],
        ['Wilt spinach briefly in a pan', 'Layer with cheese inside the tortilla', 'Grill both sides until golden'],
        'Melted cheese makes any new green feel safe and familiar.'),
    ],
  },
  {
    id: 'mushroom', name: 'Mushroom', emoji: '🍄', category: 'vegetable', texture: 'mixed', introductionDays: 12,
    tip: 'Finely chop into pasta sauce — build up to visible pieces',
    description: 'A funny little umbrella that grows in damp places and tastes earthy and rich.',
    recipes: [
      r('mushroom', 'pizza', 'Mini Mushroom Pizzas', '🍕', 'easy', '12 min', '18+ months',
        ['English muffin', '2 tbsp tomato sauce', '2 mushroom slices', 'cheese'],
        ['Spread sauce on the muffin', 'Top with thin mushroom slices and cheese', 'Bake at 200°C for 8 minutes'],
        'Pizza is one of the most trusted foods — a great mushroom debut.'),
      r('mushroom', 'omelette', 'Mushroom & Cheese Omelette', '🍳', 'easy', '10 min', '18+ months',
        ['2 eggs', '2 mushroom slices, chopped', 'pinch of cheese'],
        ['Sauté chopped mushroom in butter for 2 minutes', 'Add beaten eggs and cheese', 'Fold and cook through'],
        'Small chopped pieces feel less intimidating than whole slices.'),
      r('mushroom', 'pasta', 'Creamy Mushroom Pasta', '🍝', 'medium', '15 min', '18+ months',
        ['1/2 cup chopped mushroom', '2 tbsp cream', '1 cup cooked pasta'],
        ['Sauté mushroom in butter until soft', 'Stir in cream and a pinch of parmesan', 'Toss with pasta'],
        'A creamy sauce softens the earthy taste for first-timers.'),
    ],
  },
  {
    id: 'bellpepper', name: 'Bell Pepper', emoji: '🫑', category: 'vegetable', texture: 'crunchy', introductionDays: 12,
    tip: 'Red pepper is sweetest — start with thin strips and a dip',
    description: 'A crunchy rainbow-colored veggie shaped like a tiny lantern.',
    recipes: [
      r('bellpepper', 'strips', 'Rainbow Pepper Strips & Dip', '🌈', 'easy', '5 min', '12+ months',
        ['1 red bell pepper', '2 tbsp cream cheese'],
        ['Cut pepper into thin strips', 'Serve with cream cheese for dipping'],
        'Red peppers are the sweetest variety — always start there.'),
      r('bellpepper', 'stuffed', 'Mini Stuffed Peppers', '🧀', 'medium', '15 min', '18+ months',
        ['2 mini peppers', '2 tbsp cream cheese', 'pinch of chives'],
        ['Halve mini peppers and remove seeds', 'Fill with cream cheese and chives', 'Serve raw or lightly roasted'],
        'Letting kids fill their own pepper boats builds ownership.'),
      r('bellpepper', 'stirfry', 'Sweet Pepper Stir-Fry', '🍳', 'medium', '12 min', '18+ months',
        ['1 cup sliced pepper', '1/2 cup chicken strips', '1 tbsp soy sauce'],
        ['Stir-fry pepper strips for 3 minutes', 'Add cooked chicken and soy sauce', 'Cook 2 more minutes and serve'],
        'Pairing with a safe protein makes the new veggie feel less risky.'),
    ],
  },
  {
    id: 'cucumber', name: 'Cucumber', emoji: '🥒', category: 'vegetable', texture: 'crunchy', introductionDays: 12,
    tip: 'Peel it and cut into circles — serve with a dip',
    description: 'A cool, watery, crunchy veggie that\'s basically a refreshing drink you can chew.',
    recipes: [
      r('cucumber', 'rounds', 'Cucumber Rounds & Hummus', '🥒', 'easy', '5 min', '12+ months',
        ['1 peeled cucumber', '2 tbsp hummus'],
        ['Slice cucumber into rounds', 'Serve with hummus for dipping'],
        'Peeling removes the tougher skin many toddlers dislike.'),
      r('cucumber', 'sandwich', 'Tiny Cucumber Sandwiches', '🥪', 'easy', '8 min', '18+ months',
        ['2 slices soft bread', '4 thin cucumber slices', '1 tbsp cream cheese'],
        ['Spread cream cheese on bread', 'Layer cucumber slices', 'Cut into small triangles'],
        'Cutting into fun shapes makes new textures feel playful.'),
      r('cucumber', 'salad', 'Mini Greek Salad', '🥗', 'medium', '10 min', '18+ months',
        ['1/2 cup diced cucumber', '2 tbsp feta', 'drizzle of olive oil'],
        ['Dice cucumber into small cubes', 'Toss with crumbled feta and olive oil', 'Serve chilled'],
        'A salty cheese pairing softens the watery cucumber taste.'),
    ],
  },
  {
    id: 'corn', name: 'Corn', emoji: '🌽', category: 'vegetable', texture: 'crunchy', introductionDays: 12,
    tip: 'Corn on the cob is more fun than loose kernels',
    description: 'Golden little jewels on a cob — sweet, crunchy, and fun to eat with your hands.',
    recipes: [
      r('corn', 'cob', 'Buttery Corn on the Cob', '🌽', 'easy', '10 min', '24+ months',
        ['1 corn cob', '1 tbsp butter', 'pinch of salt'],
        ['Boil corn cob for 5 minutes', 'Roll in butter and a pinch of salt', 'Let your child hold and bite it themselves'],
        'Holding the whole cob makes corn feel like an adventure food.'),
      r('corn', 'fritters', 'Sweetcorn Fritters', '🥞', 'medium', '15 min', '18+ months',
        ['1/2 cup corn kernels', '1 egg', '2 tbsp flour'],
        ['Mix corn, egg, and flour into a batter', 'Fry small spoonfuls until golden', 'Cool slightly before serving'],
        'A pancake shape makes corn instantly more familiar.'),
      r('corn', 'chowder', 'Sweetcorn Chowder', '🥣', 'medium', '20 min', '18+ months',
        ['1 cup corn kernels', '1 small potato', '1 cup milk'],
        ['Simmer corn and diced potato in milk for 12 minutes', 'Blend half for a creamy texture', 'Serve warm'],
        'Partially blending keeps some fun pop texture for confident eaters.'),
    ],
  },
  {
    id: 'potato', name: 'Potato', emoji: '🥔', category: 'vegetable', texture: 'soft', introductionDays: 12,
    tip: 'Mashed with lots of butter first — then wedges, then new forms',
    description: 'A humble underground veggie that turns into a hundred different yummy shapes.',
    recipes: [
      r('potato', 'mash', 'Buttery Mashed Potato', '🥔', 'easy', '15 min', '12+ months',
        ['1 potato', '1 tbsp butter', 'splash of milk'],
        ['Boil peeled, cubed potato until soft', 'Mash with butter and milk', 'Serve warm'],
        'Extra butter makes the first bites of any new texture friendlier.'),
      r('potato', 'wedges', 'Crispy Potato Wedges', '🍟', 'easy', '30 min', '12+ months',
        ['1 potato, cut into wedges', '1 tbsp oil', 'pinch of salt'],
        ['Preheat oven to 200°C', 'Toss wedges in oil and salt', 'Bake 25 min, flipping once'],
        'A familiar fry shape eases the transition to new potato forms.'),
      r('potato', 'jacket', 'Jacket Potato Bar', '🧀', 'medium', '45 min', '18+ months',
        ['1 potato', 'butter', 'choice of cheese or beans'],
        ['Bake whole potato at 200°C for 40 minutes', 'Cut open and fluff the inside', 'Let your child choose their own topping'],
        'Letting kids choose their topping builds confidence and control.'),
    ],
  },
  {
    id: 'cauliflower', name: 'Cauliflower', emoji: '🤍', category: 'vegetable', texture: 'mixed', introductionDays: 12,
    tip: 'Put one small roasted floret on the plate next to a dip they like',
    description: 'Broccoli\'s pale cousin — soft, mild, and great with a favorite dip.',
    recipes: [
      r('cauliflower', 'roasted', 'Roasted Cauliflower Bites', '🤍', 'easy', '20 min', '18+ months',
        ['1 cup cauliflower florets', '1 tbsp oil', 'pinch of salt'],
        ['Preheat oven to 200°C', 'Toss florets in oil and salt', 'Roast 18 minutes until golden'],
        'Roasting brings out natural sweetness that steaming doesn\'t.'),
      r('cauliflower', 'mash', 'Cheesy Cauliflower Mash', '🧀', 'easy', '15 min', '12+ months',
        ['1 cup cauliflower', '2 tbsp cheese', '1 tbsp butter'],
        ['Boil florets until very soft', 'Mash with butter and cheese', 'Serve warm'],
        'A cheesy mash looks and tastes similar to mashed potato.'),
      r('cauliflower', 'soup', 'Creamy Cauliflower Soup', '🥣', 'medium', '20 min', '18+ months',
        ['1 cup cauliflower', '1 cup broth', '2 tbsp cream'],
        ['Simmer cauliflower in broth for 12 minutes', 'Blend until smooth', 'Stir in cream'],
        'A smooth soup is a gentle first step before whole florets.'),
    ],
  },
  {
    id: 'zucchini', name: 'Zucchini', emoji: '🥒', category: 'vegetable', texture: 'soft', introductionDays: 12,
    tip: 'Offer one soft-cooked slice. Mention nothing — just let it sit on the plate',
    description: 'A mild green squash that soaks up whatever flavor you cook it with.',
    recipes: [
      r('zucchini', 'fries', 'Baked Zucchini Fries', '🍟', 'easy', '20 min', '18+ months',
        ['1 zucchini, cut into sticks', '2 tbsp breadcrumbs', '1 egg'],
        ['Preheat oven to 200°C', 'Dip zucchini sticks in egg then breadcrumbs', 'Bake 15 minutes until crispy'],
        'A crispy coating gives zucchini a familiar crunchy-fry feel.'),
      r('zucchini', 'pancakes', 'Zucchini Pancakes', '🥞', 'medium', '15 min', '18+ months',
        ['1 cup grated zucchini', '1 egg', '2 tbsp flour'],
        ['Squeeze excess water from grated zucchini', 'Mix with egg and flour', 'Fry small patties until golden'],
        'Grating and squeezing removes the watery texture some kids dislike.'),
      r('zucchini', 'noodles', 'Buttery Zucchini Noodles', '🍝', 'medium', '10 min', '24+ months',
        ['1 zucchini, spiralized', '1 tbsp butter', 'pinch of parmesan'],
        ['Spiralize or thinly slice zucchini into noodle shapes', 'Sauté in butter for 3 minutes', 'Top with parmesan'],
        'Noodle shapes connect a new veggie to an already-loved food.'),
    ],
  },
  {
    id: 'greenbeans', name: 'Green Beans', emoji: '🫛', category: 'vegetable', texture: 'crunchy', introductionDays: 12,
    tip: 'Put 3 green beans on the plate. Snap one in half together — fun sound!',
    description: 'Long crunchy green pods that make a satisfying snap when you bend them.',
    recipes: [
      r('greenbeans', 'snap', 'Buttery Snap Beans', '🫛', 'easy', '8 min', '12+ months',
        ['1 cup green beans', '1 tbsp butter', 'pinch of salt'],
        ['Boil beans for 4 minutes until tender-crisp', 'Toss with butter and salt', 'Serve warm'],
        'Let your child snap a raw bean in half first — it\'s a fun sensory game.'),
      r('greenbeans', 'almondine', 'Crunchy Almond Beans', '🥜', 'medium', '12 min', '24+ months',
        ['1 cup green beans', '1 tbsp butter', '1 tbsp slivered almonds'],
        ['Boil beans until tender', 'Toast almonds in butter for 1 minute', 'Toss beans with the almond butter'],
        'Toasted nuts add a fun crunch contrast for confident eaters.'),
      r('greenbeans', 'fries', 'Crispy Bean Fries', '🍟', 'medium', '20 min', '18+ months',
        ['1 cup green beans', '2 tbsp breadcrumbs', '1 egg'],
        ['Preheat oven to 200°C', 'Dip beans in egg then breadcrumbs', 'Bake 15 minutes until crispy'],
        'A crunchy coating turns a vegetable into a fry-shaped favorite.'),
    ],
  },
  {
    id: 'banana', name: 'Banana', emoji: '🍌', category: 'fruit', texture: 'soft', introductionDays: 12,
    tip: 'Mash into pancakes or serve sliced with peanut butter',
    description: 'A sweet yellow fruit in its own built-in wrapper — easy to peel, easy to love.',
    recipes: [
      r('banana', 'pancakes', 'Banana Pancakes', '🥞', 'easy', '10 min', '12+ months',
        ['1 ripe banana', '1 egg', 'pinch of cinnamon'],
        ['Mash banana and mix with egg', 'Fry small spoonfuls in butter', 'Flip once golden'],
        'Only two ingredients — a fun one for little hands to help mix.'),
      r('banana', 'pops', 'Frozen Banana Pops', '🍦', 'easy', '5 min + freeze', '18+ months',
        ['1 banana, halved', '1 stick', 'sprinkle of granola'],
        ['Insert stick into banana half', 'Roll in granola', 'Freeze for 2 hours'],
        'A frozen treat shape makes banana feel like a fun dessert.'),
      r('banana', 'smoothie', 'Banana Yogurt Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['1 banana', '1/2 cup yogurt', 'splash of milk'],
        ['Blend banana, yogurt, and milk until smooth', 'Pour into a fun cup'],
        'Smoothies are a gentle way to enjoy fruit without texture worries.'),
    ],
  },
  {
    id: 'apple', name: 'Apple', emoji: '🍎', category: 'fruit', texture: 'crunchy', introductionDays: 12,
    tip: 'Try applesauce first, then soft cooked slices, then raw',
    description: 'A crisp, juicy fruit that keeps the doctor away — and tastes amazing too.',
    recipes: [
      r('apple', 'baked', 'Cinnamon Baked Apple', '🍎', 'easy', '20 min', '12+ months',
        ['1 apple, halved', '1 tsp butter', 'pinch of cinnamon'],
        ['Preheat oven to 180°C', 'Top apple halves with butter and cinnamon', 'Bake 18 minutes until soft'],
        'Baking softens the texture for kids who struggle with raw crunch.'),
      r('apple', 'dippers', 'Apple & Peanut Butter Dippers', '🥜', 'easy', '5 min', '18+ months',
        ['1 apple, sliced', '2 tbsp peanut butter'],
        ['Slice apple into thin wedges', 'Serve with peanut butter for dipping'],
        'Pairing crunchy with creamy gives two textures to enjoy at once.'),
      r('apple', 'sauce', 'Homemade Applesauce', '🍯', 'medium', '20 min', '12+ months',
        ['2 apples, peeled and diced', 'splash of water', 'pinch of cinnamon'],
        ['Simmer diced apple with water for 15 minutes', 'Mash or blend to desired texture', 'Stir in cinnamon'],
        'Homemade sauce has a chunkier, more interesting texture than store-bought.'),
    ],
  },
  {
    id: 'avocado', name: 'Avocado', emoji: '🥑', category: 'fruit', texture: 'mushy', introductionDays: 12,
    tip: 'Mash a little onto toast and call it "green butter"',
    description: 'A creamy green fruit that\'s soft like butter and packed with good energy.',
    recipes: [
      r('avocado', 'toast', 'Green Butter Toast', '🍞', 'easy', '5 min', '12+ months',
        ['1/2 avocado', '1 slice toast', 'pinch of salt'],
        ['Mash avocado with a pinch of salt', 'Spread on toast', 'Cut into fun shapes with a cookie cutter'],
        'Calling it "green butter" makes a new food feel familiar and fun.'),
      r('avocado', 'guac', 'Mild Mini Guacamole', '🥑', 'easy', '8 min', '18+ months',
        ['1/2 avocado', 'squeeze of lime', 'pinch of salt'],
        ['Mash avocado with lime and salt', 'Serve with mild tortilla chips or crackers'],
        'Letting them mash it themselves builds excitement to taste it.'),
      r('avocado', 'smoothie', 'Avocado Banana Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['1/4 avocado', '1 banana', '1 cup milk'],
        ['Blend avocado, banana, and milk until creamy', 'Pour into a cup'],
        'Blending with banana hides the avocado taste while keeping it nutritious.'),
    ],
  },
  {
    id: 'strawberry', name: 'Strawberry', emoji: '🍓', category: 'fruit', texture: 'soft', introductionDays: 12,
    tip: 'Hull and halve them — dip in yogurt or a little chocolate',
    description: 'A juicy red berry covered in tiny seeds — sweet, soft, and easy to love.',
    recipes: [
      r('strawberry', 'dippers', 'Yogurt-Dipped Strawberries', '🍓', 'easy', '5 min', '12+ months',
        ['4 strawberries, halved', '2 tbsp yogurt'],
        ['Halve and hull the strawberries', 'Serve with yogurt for dipping'],
        'Dipping turns a snack into a fun, hands-on activity.'),
      r('strawberry', 'smoothie', 'Strawberry Banana Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['4 strawberries', '1 banana', 'splash of milk'],
        ['Blend strawberries, banana, and milk until smooth', 'Pour into a fun cup'],
        'A bright pink smoothie is an exciting way to try a new fruit.'),
      r('strawberry', 'shortcake', 'Mini Strawberry Shortcake', '🍰', 'medium', '10 min', '24+ months',
        ['2 strawberries, sliced', '1 small sponge cake', '1 tbsp whipped cream'],
        ['Slice strawberries thinly', 'Layer on sponge cake with whipped cream', 'Serve as a special treat'],
        'A "treat" framing can lower resistance to a new fruit.'),
    ],
  },
  {
    id: 'blueberry', name: 'Blueberry', emoji: '🫐', category: 'fruit', texture: 'soft', introductionDays: 12,
    tip: 'Serve at room temperature — cold can put kids off',
    description: 'Tiny purple-blue berries that pop with sweet juice in every bite.',
    recipes: [
      r('blueberry', 'pancakes', 'Blueberry Pancakes', '🥞', 'easy', '12 min', '12+ months',
        ['1/4 cup blueberries', '1 cup pancake batter'],
        ['Fold blueberries into pancake batter', 'Cook small pancakes until golden', 'Serve warm'],
        'Baking inside a pancake softens the berries and bursts the flavor.'),
      r('blueberry', 'yogurt', 'Blueberry Yogurt Parfait', '🥣', 'easy', '5 min', '12+ months',
        ['1/4 cup blueberries', '1/2 cup yogurt', 'sprinkle of granola'],
        ['Layer yogurt and blueberries in a cup', 'Top with a sprinkle of granola'],
        'Layered cups make trying new fruit feel like a special dessert.'),
      r('blueberry', 'muffins', 'Blueberry Muffins', '🧁', 'medium', '25 min', '18+ months',
        ['1/4 cup blueberries', '1 cup muffin batter (any base)'],
        ['Preheat oven to 180°C', 'Fold blueberries into batter', 'Bake in muffin tin for 18 minutes'],
        'Muffins make a great freezer-friendly way to keep trying.'),
    ],
  },
  {
    id: 'grapes', name: 'Grapes', emoji: '🍇', category: 'fruit', texture: 'soft', introductionDays: 12,
    tip: 'Always halve grapes for under 5s — serve chilled or at room temp',
    description: 'Small juicy orbs that grow in bunches — squishy, sweet, and fun to count.',
    recipes: [
      r('grapes', 'frozen', 'Frozen Grape Snack', '🍇', 'easy', '5 min + freeze', '24+ months',
        ['6 grapes, halved', 'small tray'],
        ['Wash and halve grapes', 'Freeze on a tray for 2 hours', 'Serve as a cool summer snack'],
        'Frozen grapes feel like a treat and are safer than whole grapes.'),
      r('grapes', 'cheese', 'Grape & Cheese Skewers', '🧀', 'easy', '8 min', '24+ months',
        ['4 grapes, halved', '4 mild cheese cubes'],
        ['Thread grape halves and cheese cubes onto a small stick', 'Serve as a fun snack plate'],
        'Pairing with a loved cheese makes the unfamiliar fruit feel safe.'),
      r('grapes', 'smoothie', 'Grape & Apple Smoothie', '🥤', 'easy', '5 min', '18+ months',
        ['6 grapes', 'splash of apple juice', 'splash of yogurt'],
        ['Blend grapes, apple juice, and yogurt until smooth', 'Pour into a cup'],
        'A smoothie removes any worry about the grape skin texture.'),
    ],
  },
  {
    id: 'orange', name: 'Orange', emoji: '🍊', category: 'fruit', texture: 'mixed', introductionDays: 12,
    tip: 'Peel one together and enjoy the smell — that alone counts today',
    description: 'A sunny citrus fruit that smells amazing the moment you peel it.',
    recipes: [
      r('orange', 'segments', 'Simple Orange Segments', '🍊', 'easy', '5 min', '18+ months',
        ['1 orange, peeled and segmented'],
        ['Peel the orange together', 'Separate into segments', 'Remove any visible seeds'],
        'Letting your child peel it themselves builds excitement before tasting.'),
      r('orange', 'smoothie', 'Carrot Orange Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['1 orange, peeled', '1/4 cup carrot juice', 'splash of yogurt'],
        ['Blend orange segments with carrot juice and yogurt', 'Pour into a fun cup'],
        'A sweet smoothie blend softens the citrus tang for first tries.'),
      r('orange', 'parfait', 'Orange Yogurt Parfait', '🥣', 'easy', '8 min', '18+ months',
        ['1 orange, segmented', '1/2 cup yogurt', 'sprinkle of granola'],
        ['Layer yogurt and orange segments in a cup', 'Top with granola'],
        'Layering makes the tangy citrus feel balanced with something sweet.'),
    ],
  },
  {
    id: 'mango', name: 'Mango', emoji: '🥭', category: 'fruit', texture: 'soft', introductionDays: 12,
    tip: 'Put two small cubes on the plate — call it "sunshine fruit"',
    description: 'A juicy tropical fruit with golden flesh that tastes like sunshine.',
    recipes: [
      r('mango', 'cubes', 'Sunshine Mango Cubes', '🥭', 'easy', '5 min', '12+ months',
        ['1/2 mango, peeled and cubed'],
        ['Peel and cube the mango', 'Serve a few cubes on a fun plate'],
        'Calling it "sunshine fruit" adds playful excitement to a new taste.'),
      r('mango', 'smoothie', 'Mango Yogurt Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['1/2 mango', '1/2 cup yogurt', 'splash of milk'],
        ['Blend mango, yogurt, and milk until smooth', 'Pour into a cup'],
        'A creamy smoothie softens the fibrous mango texture.'),
      r('mango', 'salsa', 'Mild Mango Salsa', '🌽', 'medium', '10 min', '24+ months',
        ['1/2 mango, diced', '2 tbsp diced tomato', 'squeeze of lime'],
        ['Dice mango and tomato', 'Mix with a squeeze of lime', 'Serve with mild crackers'],
        'A salsa makes mango feel like an exciting dip rather than plain fruit.'),
    ],
  },
  {
    id: 'kiwi', name: 'Kiwi', emoji: '🥝', category: 'fruit', texture: 'soft', introductionDays: 12,
    tip: 'Slice in half and let them scoop a tiny piece with a spoon',
    description: 'A fuzzy brown fruit hiding a bright green, speckled surprise inside.',
    recipes: [
      r('kiwi', 'scoop', 'Scoop-It-Yourself Kiwi', '🥝', 'easy', '3 min', '18+ months',
        ['1 kiwi, halved'],
        ['Halve the kiwi', 'Give your child a small spoon', 'Let them scoop their own bites'],
        'Self-feeding with a spoon makes the unfamiliar texture feel controlled.'),
      r('kiwi', 'salad', 'Kiwi & Strawberry Salad', '🍓', 'easy', '5 min', '18+ months',
        ['1 kiwi, sliced', '2 strawberries, sliced'],
        ['Slice kiwi and strawberries', 'Mix together in a small bowl'],
        'Pairing with a loved fruit builds confidence for the new one.'),
      r('kiwi', 'smoothie', 'Kiwi Banana Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['1 kiwi', '1 banana', 'splash of milk'],
        ['Blend kiwi, banana, and milk until smooth', 'Pour into a cup'],
        'Blending removes any concern about the kiwi\'s tiny seeds.'),
    ],
  },
  {
    id: 'watermelon', name: 'Watermelon', emoji: '🍉', category: 'fruit', texture: 'mushy', introductionDays: 12,
    tip: 'Cut a small triangle. Spitting out a seed together makes it fun',
    description: 'A giant juicy fruit that\'s basically a sweet, refreshing drink you can bite.',
    recipes: [
      r('watermelon', 'triangle', 'Classic Watermelon Triangle', '🍉', 'easy', '5 min', '18+ months',
        ['1 small watermelon wedge'],
        ['Cut a small triangle of watermelon', 'Let your child hold and bite it themselves'],
        'Eating with hands and spitting seeds together makes it playful, not pressured.'),
      r('watermelon', 'pops', 'Watermelon Popsicles', '🧊', 'easy', '5 min + freeze', '18+ months',
        ['1 cup watermelon, blended', 'squeeze of lime'],
        ['Blend watermelon with a squeeze of lime', 'Pour into popsicle molds', 'Freeze for 4 hours'],
        'A frozen treat shape makes watermelon feel extra special.'),
      r('watermelon', 'skewers', 'Fruity Watermelon Skewers', '🍢', 'easy', '8 min', '24+ months',
        ['2 watermelon cubes', '2 melon cubes'],
        ['Cube watermelon and melon', 'Thread onto a small stick', 'Serve chilled'],
        'Combining fruits on a stick turns snack time into a game.'),
    ],
  },
  {
    id: 'peach', name: 'Peach', emoji: '🍑', category: 'fruit', texture: 'soft', introductionDays: 12,
    tip: 'Let them feel the fuzzy skin first, then offer one peeled slice',
    description: 'A soft, fuzzy fruit with sweet golden flesh hiding under its velvety skin.',
    recipes: [
      r('peach', 'baked', 'Baked Honey Peach', '🍑', 'easy', '20 min', '12+ months',
        ['1 peach, halved', '1 tsp honey', 'pinch of oats'],
        ['Preheat oven to 180°C', 'Top peach halves with honey and oats', 'Bake 18 minutes until soft'],
        'Baking softens the texture and brings out extra sweetness.'),
      r('peach', 'smoothie', 'Peach Vanilla Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['1 peach, peeled', '1/2 cup yogurt', 'pinch of vanilla'],
        ['Blend peach, yogurt, and vanilla until smooth', 'Pour into a cup'],
        'Peeling removes the fuzzy skin that some kids find off-putting.'),
      r('peach', 'parfait', 'Peach Yogurt Parfait', '🥣', 'easy', '8 min', '18+ months',
        ['1 peach, sliced', '1/2 cup yogurt', 'sprinkle of granola'],
        ['Layer yogurt and peach slices in a cup', 'Top with granola'],
        'A parfait turns trying a new fruit into a special layered treat.'),
    ],
  },
  {
    id: 'pear', name: 'Pear', emoji: '🍐', category: 'fruit', texture: 'soft', introductionDays: 12,
    tip: 'Serve one thin slice next to a fruit they already love',
    description: 'A gently sweet, bell-shaped fruit that gets juicier the riper it gets.',
    recipes: [
      r('pear', 'slices', 'Simple Pear Slices', '🍐', 'easy', '5 min', '12+ months',
        ['1 pear, thinly sliced'],
        ['Slice pear thinly', 'Serve next to a fruit they already love'],
        'Pairing with a familiar favorite lowers the pressure of trying something new.'),
      r('pear', 'baked', 'Cinnamon Baked Pear', '🍐', 'easy', '20 min', '12+ months',
        ['1 pear, halved', 'pinch of cinnamon', '1 tsp butter'],
        ['Preheat oven to 180°C', 'Top pear halves with cinnamon and butter', 'Bake 18 minutes until soft'],
        'Baking creates a soft, spoonable texture that\'s easy to manage.'),
      r('pear', 'sauce', 'Homemade Pear Sauce', '🍯', 'medium', '20 min', '12+ months',
        ['2 pears, peeled and diced', 'splash of water'],
        ['Simmer diced pear with water for 15 minutes', 'Mash or blend to desired texture'],
        'A homemade sauce is a gentle, smooth first step with pear.'),
    ],
  },
  {
    id: 'chicken', name: 'Chicken', emoji: '🍗', category: 'protein', texture: 'mixed', introductionDays: 12,
    tip: 'Start with familiar shapes — strips or nugget-style',
    description: 'A tender protein that can be shaped, dipped, and dressed up a hundred ways.',
    recipes: [
      r('chicken', 'nuggets', 'Homemade Chicken Nuggets', '🍗', 'easy', '20 min', '12+ months',
        ['1 chicken breast, cubed', '2 tbsp breadcrumbs', '1 egg'],
        ['Preheat oven to 200°C', 'Dip chicken cubes in egg then breadcrumbs', 'Bake 15 minutes until golden'],
        'A familiar nugget shape makes new protein instantly approachable.'),
      r('chicken', 'pasta', 'Mild Chicken Pasta', '🍝', 'easy', '15 min', '12+ months',
        ['1/2 cup shredded chicken', '1 cup cooked pasta', '2 tbsp tomato sauce'],
        ['Shred cooked chicken finely', 'Stir into pasta with a mild tomato sauce', 'Serve warm'],
        'Shredding into small pieces blends chicken into a beloved meal.'),
      r('chicken', 'strips', 'Dippable Chicken Strips', '🍯', 'medium', '20 min', '18+ months',
        ['1 chicken breast, sliced into strips', '1 tbsp oil', 'favorite dipping sauce'],
        ['Pan-fry strips in oil until cooked through', 'Slice into finger-friendly sizes', 'Serve with a favorite dip'],
        'Dip-friendly shapes give kids control over how much they try.'),
    ],
  },
  {
    id: 'egg', name: 'Egg', emoji: '🥚', category: 'protein', texture: 'soft', introductionDays: 12,
    tip: 'Scrambled eggs with cheese is most accepted',
    description: 'A simple oval treasure that turns fluffy and golden when you cook it.',
    recipes: [
      r('egg', 'scrambled', 'Cheesy Scrambled Eggs', '🍳', 'easy', '8 min', '12+ months',
        ['2 eggs', '1 tbsp cheese', 'pinch of butter'],
        ['Beat eggs with cheese', 'Cook gently in butter, stirring often', 'Serve soft and warm'],
        'Soft, fluffy curds are the easiest egg texture for first tries.'),
      r('egg', 'frittata', 'Mini Veggie Frittata Cups', '🧁', 'medium', '20 min', '18+ months',
        ['2 eggs', '2 tbsp diced veggies', '2 tbsp cheese'],
        ['Preheat oven to 180°C', 'Mix eggs, veggies, and cheese', 'Bake in muffin tin for 15 minutes'],
        'A muffin shape makes egg feel like a fun finger food.'),
      r('egg', 'friedrice', 'Egg Fried Rice', '🍚', 'medium', '15 min', '18+ months',
        ['1 egg, beaten', '1 cup cooked rice', '2 tbsp peas'],
        ['Scramble egg in a hot pan', 'Add cooked rice and peas', 'Stir-fry for 3 minutes'],
        'Mixing into rice gives egg a familiar, easy-to-eat backdrop.'),
    ],
  },
  {
    id: 'salmon', name: 'Salmon', emoji: '🐟', category: 'protein', texture: 'soft', introductionDays: 12,
    tip: 'Put one tiny flake on the plate — "the pink fish!"',
    description: 'A pretty pink fish that swims upstream and tastes rich and buttery.',
    recipes: [
      r('salmon', 'baked', 'Honey Glazed Salmon Flakes', '🐟', 'easy', '15 min', '18+ months',
        ['1 small salmon fillet', '1 tsp honey', '1 tsp butter'],
        ['Preheat oven to 180°C', 'Brush salmon with honey and butter', 'Bake 12 minutes and flake before serving'],
        'A sweet glaze balances the fishy flavor for first-time tasters.'),
      r('salmon', 'cakes', 'Mini Salmon Fishcakes', '🧆', 'medium', '20 min', '18+ months',
        ['1/2 cup cooked salmon, flaked', '1/2 cup mashed potato', '1 egg'],
        ['Mix flaked salmon with mashed potato and egg', 'Form small patties', 'Pan-fry until golden on both sides'],
        'A familiar potato-cake shape makes fish feel less intimidating.'),
      r('salmon', 'wrap', 'Salmon & Cream Cheese Wrap', '🌯', 'medium', '10 min', '24+ months',
        ['2 tbsp flaked salmon', '1 tbsp cream cheese', '1 small tortilla'],
        ['Spread cream cheese on tortilla', 'Add flaked salmon and roll up', 'Slice into pinwheels'],
        'Cream cheese softens the fish taste and adds a familiar creaminess.'),
    ],
  },
  {
    id: 'beans', name: 'Beans', emoji: '🫘', category: 'protein', texture: 'mushy', introductionDays: 12,
    tip: 'Serve 3 baked beans next to toast. Let them squish one between fingers',
    description: 'Tiny soft pillows packed with protein, swimming in a tasty sauce.',
    recipes: [
      r('beans', 'toast', 'Classic Beans on Toast', '🍞', 'easy', '8 min', '12+ months',
        ['1/2 cup baked beans', '1 slice toast'],
        ['Warm the baked beans', 'Spoon over a slice of toast', 'Serve warm'],
        'A globally loved combo that makes beans feel completely normal.'),
      r('beans', 'quesadilla', 'Bean & Cheese Quesadilla', '🧀', 'medium', '10 min', '18+ months',
        ['1/4 cup mashed beans', '1 tortilla', '1/2 cup cheese'],
        ['Mash beans lightly and spread on tortilla', 'Add cheese and fold in half', 'Grill until golden on both sides'],
        'Mashing into a quesadilla hides the bean texture inside a loved food.'),
      r('beans', 'chilli', 'Mild Bean Chilli', '🌶️', 'medium', '20 min', '24+ months',
        ['1/2 cup beans', '1/4 cup diced tomato', 'pinch of mild spice'],
        ['Simmer beans and tomato together for 12 minutes', 'Season very mildly', 'Serve with rice or bread'],
        'Keep spice minimal at first — flavor can build up over future tries.'),
    ],
  },
  {
    id: 'meatballs', name: 'Meatballs', emoji: '🍖', category: 'protein', texture: 'mixed', introductionDays: 12,
    tip: 'Serve one mini meatball with pasta they already like',
    description: 'A juicy little ball of savory goodness, perfect for dipping in sauce.',
    recipes: [
      r('meatballs', 'spaghetti', 'Mini Meatball Spaghetti', '🍝', 'medium', '25 min', '18+ months',
        ['4 mini meatballs', '1 cup cooked spaghetti', '2 tbsp tomato sauce'],
        ['Cook mini meatballs in a pan until browned through', 'Warm with tomato sauce', 'Serve over spaghetti'],
        'A trusted pasta dish is the perfect vehicle for trying meatballs.'),
      r('meatballs', 'sub', 'Mini Meatball Sub', '🥪', 'medium', '15 min', '24+ months',
        ['2 mini meatballs', '1 small soft roll', '1 tbsp cheese'],
        ['Warm cooked meatballs in sauce', 'Place in a soft roll with melted cheese', 'Slice into bite-sized pieces'],
        'Cutting into small pieces makes a sub feel manageable for tiny hands.'),
      r('meatballs', 'soup', 'Mini Meatball Soup', '🥣', 'medium', '20 min', '18+ months',
        ['4 mini meatballs', '1 cup mild broth', '2 tbsp small pasta'],
        ['Simmer meatballs in broth for 10 minutes', 'Add small pasta and cook until tender', 'Serve warm'],
        'A soothing soup format makes a new protein feel cozy, not scary.'),
    ],
  },
  {
    id: 'peanutbutter', name: 'Peanut Butter', emoji: '🥜', category: 'protein', texture: 'mushy', introductionDays: 12,
    tip: 'Spread a thin layer on toast or a cracker they already enjoy',
    description: 'A creamy, nutty spread that turns plain toast into something special.',
    recipes: [
      r('peanutbutter', 'toast', 'Peanut Butter Banana Toast', '🍞', 'easy', '5 min', '12+ months',
        ['1 slice toast', '1 tbsp peanut butter', '1/2 banana, sliced'],
        ['Spread a thin layer of peanut butter on toast', 'Top with banana slices', 'Cut into fun shapes'],
        'A thin layer is easier to manage than a thick spoonful for first tries.'),
      r('peanutbutter', 'antsonalog', 'Ants on a Log', '🐜', 'easy', '5 min', '24+ months',
        ['1 celery stick', '1 tbsp peanut butter', '1 tbsp raisins'],
        ['Fill celery stick with peanut butter', 'Top with a row of raisins', 'Serve as a fun snack'],
        'The silly "ants on a log" name turns snack time into a game.'),
      r('peanutbutter', 'noodles', 'Mild Peanut Noodles', '🍜', 'medium', '15 min', '24+ months',
        ['1 tbsp peanut butter', '1 tsp soy sauce', '1 cup cooked noodles'],
        ['Whisk peanut butter with soy sauce and a splash of warm water', 'Toss with cooked noodles', 'Serve warm'],
        'A noodle dish is a fun, low-pressure way to try peanut flavor.'),
    ],
  },
  {
    id: 'turkey', name: 'Turkey', emoji: '🍗', category: 'protein', texture: 'mixed', introductionDays: 12,
    tip: 'Offer one small slice rolled up — fun finger food shape',
    description: 'A lean, mild-tasting meat that\'s a gentle cousin of chicken.',
    recipes: [
      r('turkey', 'rollups', 'Turkey Cheese Roll-Ups', '🧀', 'easy', '5 min', '18+ months',
        ['2 thin turkey slices', '2 cheese slices'],
        ['Lay turkey slice flat', 'Top with cheese and roll up', 'Slice into bite-sized rounds'],
        'A fun roll-up shape makes a new meat feel like finger food.'),
      r('turkey', 'meatballs', 'Mini Turkey Meatballs', '🍖', 'medium', '20 min', '18+ months',
        ['1/2 cup ground turkey', '2 tbsp breadcrumbs', '1 egg'],
        ['Mix turkey, breadcrumbs, and egg', 'Form small balls', 'Bake at 200°C for 15 minutes'],
        'Mild turkey meatballs are gentler in flavor than beef for first tries.'),
      r('turkey', 'wrap', 'Turkey & Avocado Wrap', '🌯', 'medium', '10 min', '24+ months',
        ['2 turkey slices', '2 tbsp mashed avocado', '1 small tortilla'],
        ['Spread avocado on tortilla', 'Layer turkey slices', 'Roll up and slice into pinwheels'],
        'Pairing with a soft, familiar avocado makes turkey feel approachable.'),
    ],
  },
  {
    id: 'tofu', name: 'Tofu', emoji: '🧊', category: 'protein', texture: 'soft', introductionDays: 12,
    tip: 'Serve one soft cube with a dip — let them touch before tasting',
    description: 'A soft, wobbly white square that takes on the flavor of anything around it.',
    recipes: [
      r('tofu', 'cubes', 'Soft Dippable Tofu Cubes', '🧊', 'easy', '8 min', '12+ months',
        ['4 soft tofu cubes', '1 tbsp mild dipping sauce'],
        ['Cut tofu into small cubes', 'Serve with a mild dipping sauce', 'Let your child touch and explore first'],
        'Touching before tasting helps kids feel safe with the wobbly texture.'),
      r('tofu', 'crispy', 'Crispy Baked Tofu Bites', '🍟', 'medium', '25 min', '18+ months',
        ['1/2 cup tofu, cubed', '1 tbsp cornstarch', '1 tbsp oil'],
        ['Preheat oven to 200°C', 'Toss tofu cubes in cornstarch and oil', 'Bake 20 minutes until crispy'],
        'A crispy outside gives tofu a fun, fry-like texture kids recognize.'),
      r('tofu', 'stirfry', 'Mild Tofu Veggie Stir-Fry', '🍳', 'medium', '15 min', '24+ months',
        ['1/2 cup tofu, cubed', '1/4 cup mixed veggies', '1 tsp soy sauce'],
        ['Pan-fry tofu cubes until lightly golden', 'Add veggies and soy sauce', 'Cook 3 more minutes'],
        'Pairing tofu with familiar veggies builds a complete, balanced bite.'),
    ],
  },
  {
    id: 'pasta', name: 'Pasta', emoji: '🍝', category: 'grain', texture: 'soft', introductionDays: 12,
    tip: 'Serve plain pasta with butter. Familiar shape, zero pressure',
    description: 'Twisty, curly noodles in every shape — comfort food in its purest form.',
    recipes: [
      r('pasta', 'butter', 'Plain Buttery Pasta', '🍝', 'easy', '10 min', '12+ months',
        ['1 cup cooked pasta', '1 tbsp butter', 'pinch of parmesan'],
        ['Cook pasta according to package', 'Toss with butter', 'Sprinkle with parmesan'],
        'Keep it simple — plain butter pasta is the gentlest starting point.'),
      r('pasta', 'hiddenveg', 'Hidden Veggie Bolognese', '🍅', 'medium', '25 min', '18+ months',
        ['1 cup cooked pasta', '1/4 cup blended veggies', '2 tbsp meat sauce'],
        ['Blend cooked carrot and courgette into the meat sauce', 'Simmer for 10 minutes', 'Toss with pasta'],
        'Blending vegetables smooth keeps the familiar taste while adding nutrition.'),
      r('pasta', 'pesto', 'Mild Pesto Pasta', '🌿', 'medium', '12 min', '18+ months',
        ['1 cup cooked pasta', '1 tsp mild pesto', '1 tbsp butter'],
        ['Mix pesto with melted butter', 'Toss with warm pasta', 'Serve with extra parmesan'],
        'A small amount of pesto introduces new flavor without overwhelming it.'),
    ],
  },
  {
    id: 'oatmeal', name: 'Oatmeal', emoji: '🥣', category: 'grain', texture: 'mushy', introductionDays: 12,
    tip: 'Make it together and add a topping they already love',
    description: 'A warm, cozy bowl of oats that\'s like a blank canvas for tasty toppings.',
    recipes: [
      r('oatmeal', 'overnight', 'Overnight Oats', '🥣', 'easy', '5 min + fridge', '18+ months',
        ['1/2 cup oats', '1/2 cup milk', '1 tbsp yogurt'],
        ['Mix oats, milk, and yogurt in a jar', 'Refrigerate overnight', 'Top with favorite fruit in the morning'],
        'Letting kids pick their own topping builds excitement to eat it.'),
      r('oatmeal', 'cookies', 'No-Bake Oat Banana Cookies', '🍪', 'easy', '15 min', '18+ months',
        ['1 ripe banana', '1/2 cup oats', '1 tsp honey'],
        ['Mash banana and mix with oats and honey', 'Form small cookie shapes', 'Bake at 180°C for 12 minutes'],
        'A cookie shape makes oats feel like a fun treat, not a chore.'),
      r('oatmeal', 'toppingsbar', 'Oatmeal Toppings Bar', '🍓', 'easy', '10 min', '12+ months',
        ['1/2 cup cooked oatmeal', 'small bowls of fruit, honey, cinnamon'],
        ['Cook plain oatmeal', 'Set out small bowls of toppings', 'Let your child build their own bowl'],
        'Giving choice and control makes trying new toppings feel like a game.'),
    ],
  },
  {
    id: 'rice', name: 'Rice', emoji: '🍚', category: 'grain', texture: 'soft', introductionDays: 12,
    tip: 'Serve plain rice with a pat of butter on the side of the plate',
    description: 'Soft little grains that soak up flavor from anything you cook with them.',
    recipes: [
      r('rice', 'friedrice', 'Simple Fried Rice', '🍳', 'easy', '12 min', '18+ months',
        ['1 cup cooked rice', '1 egg', '2 tbsp peas'],
        ['Scramble egg in a hot pan', 'Add cold cooked rice and peas', 'Stir-fry for 4 minutes'],
        'Day-old rice fries up firmer, which many kids prefer.'),
      r('rice', 'pudding', 'Creamy Rice Pudding', '🍮', 'medium', '20 min', '18+ months',
        ['1/2 cup cooked rice', '1 cup milk', '1 tsp vanilla'],
        ['Simmer rice in milk for 15 minutes, stirring often', 'Stir in vanilla', 'Serve warm or chilled'],
        'A sweet pudding format makes rice feel like a comforting dessert.'),
      r('rice', 'curry', 'Mild Rice & Curry', '🍛', 'medium', '20 min', '24+ months',
        ['1 cup plain rice', '1/4 cup mild coconut curry sauce'],
        ['Cook rice plain', 'Serve a small pool of very mild curry sauce alongside', 'Let your child dip rice into the sauce'],
        'Keeping the rice and sauce separate lets kids control the intensity.'),
    ],
  },
  {
    id: 'pancakes', name: 'Pancakes', emoji: '🥞', category: 'grain', texture: 'soft', introductionDays: 12,
    tip: 'Let them help pour the batter — making it together builds comfort',
    description: 'Fluffy golden discs perfect for stacking, topping, and devouring.',
    recipes: [
      r('pancakes', 'classic', 'Classic Fluffy Pancakes', '🥞', 'easy', '15 min', '12+ months',
        ['1 cup pancake batter', '1 tbsp butter'],
        ['Let your child help pour the batter', 'Cook on a buttered pan until golden', 'Serve with fruit or syrup'],
        'Helping make the batter builds ownership and excitement to eat it.'),
      r('pancakes', 'blueberry', 'Blueberry Pancakes', '🫐', 'easy', '15 min', '12+ months',
        ['1 cup pancake batter', '1/4 cup blueberries'],
        ['Fold blueberries into the batter', 'Cook small pancakes until golden', 'Serve warm'],
        'Fruit folded into a loved food is an easy way to add variety.'),
      r('pancakes', 'savoury', 'Savoury Cheese Pancakes', '🧀', 'medium', '15 min', '18+ months',
        ['1 cup pancake batter', '1/4 cup grated cheese'],
        ['Mix cheese into the batter', 'Cook small pancakes until golden', 'Serve with a side of soup'],
        'A savoury twist introduces new flavor while keeping the loved shape.'),
    ],
  },
  {
    id: 'bread', name: 'Bread', emoji: '🍞', category: 'grain', texture: 'soft', introductionDays: 12,
    tip: 'Offer one small new bread shape or type next to their usual one',
    description: 'A soft, fluffy staple that turns into toast, sandwiches, and so much more.',
    recipes: [
      r('bread', 'comparison', 'Bread Type Taste Test', '🍞', 'easy', '5 min', '12+ months',
        ['1 slice usual bread', '1 small slice new bread'],
        ['Cut both breads into small matching pieces', 'Let your child compare side by side', 'No pressure to finish either'],
        'Comparing side by side turns trying something new into a game.'),
      r('bread', 'frenchtoast', 'Simple French Toast', '🍳', 'easy', '12 min', '18+ months',
        ['1 slice bread', '1 egg', 'pinch of cinnamon'],
        ['Dip bread in beaten egg with cinnamon', 'Fry in butter until golden on both sides', 'Cut into strips'],
        'Strip shapes make new bread types feel like a fun dippable snack.'),
      r('bread', 'pizza', 'Mini Bread Pizza', '🍕', 'easy', '12 min', '18+ months',
        ['1 slice bread', '2 tbsp tomato sauce', '2 tbsp cheese'],
        ['Top bread with sauce and cheese', 'Grill or bake until cheese melts', 'Cut into small squares'],
        'Pizza framing makes any bread type feel instantly exciting.'),
    ],
  },
  {
    id: 'soup', name: 'Soup', emoji: '🍲', category: 'grain', texture: 'mushy', introductionDays: 12,
    tip: 'Serve a small smooth soup in a fun cup. Stirring and blowing on it counts',
    description: 'A warm, cozy bowl of goodness that\'s fun to stir, blow on, and slurp.',
    recipes: [
      r('soup', 'tomato', 'Classic Tomato Soup', '🍅', 'easy', '15 min', '12+ months',
        ['1 cup tomato', '1/2 cup broth', '1 tbsp cream'],
        ['Simmer tomato in broth for 10 minutes', 'Blend smooth', 'Stir in cream'],
        'Serving in a fun cup with a straw makes soup feel playful.'),
      r('soup', 'chickennoodle', 'Mild Chicken Noodle Soup', '🍜', 'medium', '20 min', '18+ months',
        ['1/4 cup shredded chicken', '1 cup mild broth', '2 tbsp small pasta'],
        ['Simmer broth with chicken for 8 minutes', 'Add small pasta and cook until tender', 'Serve warm'],
        'Small noodle shapes give kids something fun and familiar to find.'),
      r('soup', 'carrotginger', 'Carrot & Ginger Soup', '🥕', 'medium', '20 min', '18+ months',
        ['1 cup roasted carrot', '1 cup broth', '2 tbsp cream'],
        ['Simmer roasted carrot in broth for 10 minutes', 'Blend until smooth', 'Stir in cream'],
        'A smooth, sweet soup is gentle for soup-texture beginners.'),
    ],
  },
  {
    id: 'cereal', name: 'Cereal', emoji: '🥣', category: 'grain', texture: 'crunchy', introductionDays: 12,
    tip: 'Pour a small new cereal next to their usual one — let them compare',
    description: 'Crunchy little bites that turn breakfast into a fun bowl of variety.',
    recipes: [
      r('cereal', 'comparison', 'Cereal Compare Bowl', '🥣', 'easy', '3 min', '18+ months',
        ['2 tbsp usual cereal', '2 tbsp new cereal', 'splash of milk'],
        ['Pour both cereals into separate sides of a bowl', 'Add a splash of milk', 'Let your child compare textures'],
        'Side-by-side comparison feels like an experiment, not a demand.'),
      r('cereal', 'trailmix', 'Cereal Trail Mix', '🥜', 'easy', '5 min', '24+ months',
        ['2 tbsp cereal', '1 tbsp raisins', '1 tbsp banana chips'],
        ['Mix cereal with raisins and banana chips', 'Serve in a small fun bowl'],
        'Mixing with loved snacks makes a new cereal feel less risky.'),
      r('cereal', 'yogurtbark', 'Cereal Yogurt Bark', '🍫', 'medium', '10 min + freeze', '24+ months',
        ['1/2 cup yogurt', '2 tbsp cereal', 'sprinkle of berries'],
        ['Spread yogurt on a tray', 'Sprinkle with cereal and berries', 'Freeze for 2 hours, then break into pieces'],
        'A crunchy frozen treat turns cereal into a fun snack shape.'),
    ],
  },
  {
    id: 'cheese', name: 'Cheese', emoji: '🧀', category: 'dairy', texture: 'soft', introductionDays: 12,
    tip: 'Offer string cheese — pulling it apart is half the fun',
    description: 'A creamy, savory treat that comes in a hundred shapes, colors, and flavors.',
    recipes: [
      r('cheese', 'string', 'Pull-Apart String Cheese', '🧀', 'easy', '2 min', '12+ months',
        ['1 string cheese stick'],
        ['Hand your child the string cheese', 'Show them how to peel a string off', 'Let them pull and eat at their own pace'],
        'The peeling action itself is a fun sensory activity kids enjoy.'),
      r('cheese', 'toast', 'Cheese on Toast', '🍞', 'easy', '8 min', '12+ months',
        ['1 slice bread', '2 tbsp grated cheese'],
        ['Top bread with grated cheese', 'Grill until melted and bubbly', 'Cut into small triangles'],
        'Melted cheese on toast is one of the most universally loved combos.'),
      r('cheese', 'muffins', 'Cheese & Veggie Muffins', '🧁', 'medium', '25 min', '18+ months',
        ['1/4 cup grated cheese', '1 cup savoury muffin batter', '2 tbsp diced veggies'],
        ['Preheat oven to 180°C', 'Mix cheese and veggies into batter', 'Bake in muffin tin for 18 minutes'],
        'A muffin shape makes cheese feel like a fun lunchbox snack.'),
    ],
  },
  {
    id: 'yogurt', name: 'Yogurt', emoji: '🥛', category: 'dairy', texture: 'mushy', introductionDays: 12,
    tip: 'Let them stir in their own fruit topping — ownership helps',
    description: 'A cool, creamy, tangy treat that loves to be mixed with fruit and honey.',
    recipes: [
      r('yogurt', 'parfait', 'Build-Your-Own Yogurt Parfait', '🥣', 'easy', '5 min', '12+ months',
        ['1/2 cup yogurt', '2 tbsp fruit', '1 tbsp granola'],
        ['Layer yogurt, fruit, and granola in a cup', 'Let your child add their own toppings'],
        'Ownership over toppings makes yogurt feel like a fun project, not a food demand.'),
      r('yogurt', 'bark', 'Frozen Yogurt Bark', '🍫', 'medium', '10 min + freeze', '18+ months',
        ['1/2 cup yogurt', '2 tbsp diced fruit'],
        ['Spread yogurt thinly on a tray', 'Sprinkle with diced fruit', 'Freeze for 2 hours and break into pieces'],
        'A crunchy frozen format is a fun twist on familiar yogurt.'),
      r('yogurt', 'dip', 'Yogurt Fruit Dip', '🍓', 'easy', '5 min', '12+ months',
        ['1/2 cup yogurt', '1 tsp honey'],
        ['Mix yogurt with a little honey', 'Serve with sliced fruit for dipping'],
        'Using yogurt as a dip pairs it with foods your child already enjoys.'),
    ],
  },
  {
    id: 'milk', name: 'Milk', emoji: '🥛', category: 'dairy', texture: 'soft', introductionDays: 12,
    tip: 'Offer a small new cup alongside their usual drink — no swap required',
    description: 'A creamy white drink that comes from cows, goats, plants, and more.',
    recipes: [
      r('milk', 'comparison', 'Milk Taste-Test Cups', '🥛', 'easy', '3 min', '12+ months',
        ['2 tbsp usual milk', '2 tbsp new milk type'],
        ['Pour both milks into small matching cups', 'Let your child try a sip of each', 'No pressure to finish either'],
        'Tiny side-by-side sips feel like an experiment, not a big commitment.'),
      r('milk', 'smoothie', 'Simple Fruit Milk Smoothie', '🥤', 'easy', '5 min', '12+ months',
        ['1/2 cup milk', '1/2 banana', 'splash of vanilla'],
        ['Blend milk, banana, and vanilla until smooth', 'Pour into a fun cup'],
        'Blending milk with a loved fruit makes the new flavor easy to enjoy.'),
      r('milk', 'hotchoc', 'Warm Mild Hot Chocolate', '🍫', 'easy', '8 min', '24+ months',
        ['1 cup milk', '1 tsp cocoa', '1 tsp honey'],
        ['Warm milk gently on the stove', 'Whisk in cocoa and honey', 'Serve warm, not hot'],
        'A cozy warm treat is a great way to try a new type of milk.'),
    ],
  },
];
